### ISSUE TITLE
Not Creating Multiple Models

### ISSUE THREAD

**Issue by ghost** [pwestling/battlescribe-roster-parser#1]
**Describe the bug**
When the app creates my list, it will only create a single model of each type in some units, when it requires duplicate models. For instance, a unit of Terminators that has one Champion and four combi-bolter armed models will only create a unit with one Champion and one combi-bolter armed model. It does the same with Havocs, but not other units such as Chaos Cultists.

**Expected behavior**
I'd like for the app to generate the correct amount of models in a unit when I create my army list.

**Upload the Roster**
GitHub won't let me upload.Roz files. When I try, it says...

"We don't support that file type. Try again with a GIF, JPEG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP."

**Comment by pwestling** [comment]
A .rosz file is actually just a zip file, so you can rename it and then github should allow the upload. In the meantime I'll try to find your request in the logs.

**Comment by ghost** [comment]
Ah, here you go then...

[40K Cult of The One (2K Daemonic Mk2).zip](https://github.com/pwestling/battlescribe-roster-parser/files/3376191/40K.Cult.of.The.One.2K.Daemonic.Mk2.zip)

**Comment by pwestling** [comment]
Awesome, thanks! I think I see where the bug is (the data file author structured these units in a different way that the code isn't accounting for), let me see if I can squish it. Thanks so much for filing the bug report!

**Comment by ghost** [comment]
No worries. Love the app! Any plans to include Kill Team and Apocalypse?

**Comment by pwestling** [comment]
I hadn't even thought about it yet honestly. I'll have to see how similar the roster file structures are to see if it's feasible.

**Comment by ghost** [comment]
Regardless, this app makes army building soooo much easier. Thanks for putting it together!

**Comment by pwestling** [comment]
Alright, I think I have it fixed. I tried with your terminators and it seemed to work as I would expect. Can you verify on your end and confirm here that you don't see any more cases of missing models?

**Comment by ghost** [comment]
The Terminators work now, but my Havocs and Dark Apostle are missing now. The Dark Disciple and Aspiring Champion of the Havocs strangely still show up though.

**Comment by pwestling** [comment]
Ah shoot I missed those. Even weirder structure this time. I will find a way to detect these, but going to have to sleep for tonight so won't get to it until tomorrow.

**Comment by ghost** [comment]
No worries. Appreciate it.

**Comment by pwestling** [comment]
Ok, added a new heuristic that seems to work, at least for your list and other edge cases I know about. Give it one more try for me?

**Comment by ghost** [comment]
It works! Fantastic job! I'll be using this a lot!
