### ISSUE TITLE
Nested Weapon Selections Missing

### ISSUE THREAD

**Issue by RelicLord** [pwestling/battlescribe-roster-parser#13]
**Describe the Bug**
Vehicles with sub-selections of weapons do not show those weapons on their model description. For example, "2x Heavy Bolters" is missing in the model description for the Valkyrie, but the bolters do show up correctly on the full data sheet.

In the attached file, you can see that other weapon selections with a plus next to them (ex. Baneblade Sponsons) share this issue. This may be more of an issue with how the data itself is organized, since the same nesting is used for squads and other mixed units.

[Test Valk.zip](https://github.com/pwestling/battlescribe-roster-parser/files/3639037/Test.Valk.zip)

**Comment by pwestling** [comment]
I will find some time tomorrow to see if there's a way to resolve this. The data structure does often make it very hard to resolve this while not accidentally adding weapons that shouldn't be there in other cases, so we'll see.

**Comment by pwestling** [comment]
I think I have this issue fixed - please try generating the army again and see if all the guns are there now, and let me know if you continue to have any issues.

**Comment by RelicLord** [comment]
Works like a charm.  I didn't expect such a quick response, let alone a fix.

Thank you for the update, and for the tool itself.

**Comment by pwestling** [comment]
Glad it works for you! Thanks for the bug report.
