### ISSUE TITLE
Support Multi Model Units

### ISSUE THREAD

**Issue by Streyder** [pwestling/battlescribe-roster-parser#14]
Hey there!

There are some units in the game which consist of multiple different models. This happens for Squads and Squad Sergeants for example.

However this does not seem to work for other relationships. An example is the Thunderfire Cannon which comes with a Techmarine Gunner. I can only select a model for the cannon but not its gunner. 

The Cannon is spawned with all the info about both units, although it should be split between the units.

Best
Streyder

**Comment by pwestling** [comment]
The issue with the Thunderfire Cannon (and a bunch of others) has been fixed
