### ISSUE TITLE
Intercessors do not have their main weapon imported

### ISSUE THREAD

**Issue by dode74** [pwestling/battlescribe-roster-parser#19]
**Describe the bug**
Weapon details for the Space Marines intercessor do not include the Bolt Rifle.

**Expected behavior**
A line should be there for the Bolt Rifle.

**Upload the Roster**
[1250 RG Tournamentx.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4334438/1250.RG.Tournamentx.zip)

**Comment by pwestling** [comment]
Fixed by #23
