### ISSUE TITLE
Datasheet scripting does not appear to be working

### ISSUE THREAD

**Issue by dunny85** [pwestling/battlescribe-roster-parser#20]
**Describe the bug**
I'm a new user but this looks like a great tool, thanks. When I create my army, pressing 1 on the model does not bring up the datasheet. 

I have "Enable model scripting" selected on the upload. The descriptions are showing correctly, just not the datasgeet

**Expected behavior**
That the datasheet should show when I press 1.

**Upload the Roster**
[CA19 - ambitious surge.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4411377/CA19.-.ambitious.surge.zip)

Thanks for any help!

**Comment by pwestling** [comment]
Happy to look into this further, but as an initial check can you try changing the key for Scripting Button 1 in the key bindings in TTS to something else (like "K" or some other letter with no binding), and try it again using that? Want to make sure it's not some key binding issue.

**Comment by pwestling** [comment]
I've confirmed that this seems to be working on my side for this roster - please try again on your side with some new scripting button set and let me know what happens

**Comment by dunny85** [comment]
Hi Porter,

Just tried this and it works perfectly when switching to an unused key -
very happy!

Thanks
James

**Comment by pwestling** [comment]
Awesome!
