### ISSUE TITLE
Bolt Action Compatibility

### ISSUE THREAD

**Issue by UpperSideBand** [pwestling/battlescribe-roster-parser#22]
**Is your feature request related to a problem? Please describe.**
Would love to use your app to create Army lists for Bolt Action v2.0

**Describe the solution you'd like**
Can you please make Battlescribe2TTS compatible with Bolt Action v2.0?

**Comment by pwestling** [comment]
Just to set expectations, I do not play Bolt Action and I'm unlikely to get to this in the near future, sorry. I'll leave this open on the off chance the pandemic leaves me with more free time than I expect though.

Also, the code is 100% open source - if anyone in the Bolt Action community that you can find writes Haskell and wants to do the work, I'll 100% be helpful!
