### ISSUE TITLE
Stalker bolt rifle

### ISSUE THREAD

**Issue by GOTOTHEUNKNOWN** [pwestling/battlescribe-roster-parser#23]
stalker bolt rifle is not recognized by the tool and as such assumes that my space marne intersessors are recognized to have a bolt rife and not a stalker rifle

**Comment by pwestling** [comment]
Hard to tell, but I think this is a duplicate of https://github.com/pwestling/battlescribe-roster-parser/issues/19. If you don't think so, please open a new ticket with a roster demonstrating the issue.
