### ISSUE TITLE
Opening the Datasheet window

### ISSUE THREAD

**Issue by LienLeinad** [pwestling/battlescribe-roster-parser#25]
**Describe the bug**
For some reason when I open the window in TTS multiplayer with someone else, it opens the window in their screen too
**Expected behavior**
It doesn't open when I open it for the other player
**Upload the Roster**
Rename your .rosz file to have the .zip extension, then drag and drop it here
n/a

**Comment by pwestling** [comment]
Is there any chance that both players had not selected a color when this was happening? The visibility is by color. If you can try again and note what color each player was, that would help me out. Thanks!

**Comment by pwestling** [comment]
Going to close this for now, please open a new ticket if you're still having issues here, or contact me on the Warhammer 40k TTS discord

**Comment by LienLeinad** [comment]
Sorry just saw this now. It was cause we didn't select a color, thank you!
