### ISSUE TITLE
Captain Lysander not being imported for Imperial Fists

### ISSUE THREAD

**Issue by mattlore** [pwestling/battlescribe-roster-parser#26]
So there appears to be a bug in regards to the character model Captain Lysander. I uploaded the attached list a couple of times and Captain Lysander is missing from the model selection process. I have also tried to upload a list with JUST Lysander and it was still missing

[V3_Imperial_fists_battalion_final2.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4441375/V3_Imperial_fists_battalion_final2.zip)

**Comment by pwestling** [comment]
I'm able to reproduce this. Not sure what's going on with it, will try to solve this weekend.

**Comment by pwestling** [comment]
I think this should be fixed now
