### ISSUE TITLE
Tzaangor enlightened incorrect model count

### ISSUE THREAD

**Issue by ABF06** [pwestling/battlescribe-roster-parser#27]
I created a Thousand Sons list with a tzaangor enlightened unit, which includes 1 aviarch and 2 tzaangor enlightened, but the script generated 4 models, 1 aviarch, 2 enlightened and 1 "Tzaangor Enlightened" (which is the name of the unit).

**Expected behavior**
It should've generated only 1 aviarch and 2 enlightened instead of 4 models for this unit.

[Thousand sons TTS 1250 Pt .zip](https://github.com/pwestling/battlescribe-roster-parser/files/4453589/Thousand.sons.TTS.1250.Pt.zip)

**Comment by pwestling** [comment]
I think this should be fixed now. Please open a new ticket if you're still seeing it.
