### ISSUE TITLE
battlescribe2tts website code

### ISSUE THREAD

**Issue by SubversionIndustries** [pwestling/battlescribe-roster-parser#29]
It appears that the website is not currently generating the code when uploading a roster.

**Comment by pwestling** [comment]
Can you attach the roster you're trying to upload?

**Comment by SubversionIndustries** [comment]
> Can you attach the roster you're trying to upload?

Yep! Attached.

[2K - 1 AoA - Cov Batt, Cult Batt, Kab Spear, Cult Batt.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4507698/2K.-.1.AoA.-.Cov.Batt.Cult.Batt.Kab.Spear.Cult.Batt.zip)

**Comment by pwestling** [comment]
Uploading this roster generates a code for me. Can you tell me more about what you're seeing? If you open the developer console (https://balsamiq.com/support/faqs/browserconsole/) are there any errors or text printed in there?

**Comment by Goblin137** [comment]
I'm having the same issue. 

The site says NetworkError and the console shows the following

(https://user-images.githubusercontent.com/64739752/80916988-15290300-8d54-11ea-8bf8-0f45118f9a44.PNG)

Any thoughts?

Edit: I've tried this on Chrome and Microsoft Edge browsers with the same outcome.

**Comment by SubversionIndustries** [comment]
[battlescribe2tts.net-1588527638068.log](https://github.com/pwestling/battlescribe-roster-parser/files/4571147/battlescribe2tts.net-1588527638068.log)

**Comment by SubversionIndustries** [comment]
Notably, I just now tried it in IE, Firefox, and Edge, and they all worked. In Chrome, it lets me select the file, but never shows "uploading".

**Comment by pwestling** [comment]
I haven't seen any other reports of this. Are you guys still seeing it?

**Comment by pwestling** [comment]
Going to close this as I suspect it was a website downtime issue. Please re open if you're still seeing this happen.

**Comment by Cothrom** [comment]
I am having a similar issue
