### ISSUE TITLE
Multiple buttons created for wargear

### ISSUE THREAD

**Issue by cronsOP125** [pwestling/battlescribe-roster-parser#3]
Multiple buttons are created for wargear options that have sub-menus. E.g. Sicarian Infiltrator Princeps creates 2 buttons, one for the Princeps with no wargear, and one called Taser goad & Flechette blaster. Talos Pain Engine creates 3: 1 called Talos with no wargear, one called Talos Pain Engine with correct wargear, and one called 2 Haywire blasters
[Army Lists.zip](https://github.com/pwestling/battlescribe-roster-parser/files/3379280/Army.Lists.zip)

**Comment by pwestling** [comment]
I've pushed an update that should hopefully address this. Please take a look and let me know if you're still having issues. If there are further specific units giving you trouble if you can upload a roster file containing just the problematic units that would be helpful.

**Comment by pwestling** [comment]
Thanks for the report - I was able to clean up a bunch of cases where models were incorrectly reported. If you see more issues in the future please open a new issue with an example roster
