### ISSUE TITLE
Bloodletters Icon and Instrument Not Separate Wargear

### ISSUE THREAD

**Issue by Plathulu** [pwestling/battlescribe-roster-parser#32]
I was creating a tiny Khorne army, with a decent amount of Bloodletters. When I imported the list to the Battlescribe2TTs Create Army, it treated the Daemonic Icon and Instrument of Chaos as gear for all the Bloodletters rather than having them be separate models.

The Icon and Instrument are supposed to be on individual Bloodletters, I think specifically separate from each other too. It would make sense if it asked for an extra model each wargear, so one for the Bloodletters themselves, one for the Icon, and one for the Instrument (and one for the Bloodreaper, but he doesn't factor in atm).

[500pKhorneForFun.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4474004/500pKhorneForFun.zip)

**Comment by pwestling** [comment]
Sorry for the long delay - the mechanics on the backend for this were tricky. This should be fixed now
