### ISSUE TITLE
"Hellblaster Squad" shows up as a unit to script.

### ISSUE THREAD

**Issue by SupaChigga** [pwestling/battlescribe-roster-parser#33]
In the spacemarines: Hellblaster Squad: It separates the hellblaster sergeant and hellblasters away from "hellblaster squad"

The main weapons from hellblaster squad should be automatically applied to the hellblaster sergeant and hellblasters. "Hellblaster squad" should not show up as a unit to script.

[Dark Imperium Box Space Marines - Copy.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4478364/Dark.Imperium.Box.Space.Marines.-.Copy.zip)

**Comment by pwestling** [comment]
I think this should be fixed now. Please open a new ticket if you're still seeing issues.
