### ISSUE TITLE
Error in BS2TTS for Daemon Prince Model.

### ISSUE THREAD

**Issue by Znar1** [pwestling/battlescribe-roster-parser#34]
**Describe the bug**
- One using the Battlescribe 2TTS tool it only has me pick one daemon prince model, though both are equipped differently. Thus when it loads the army it uses the same model twice. 

**Expected behavior**
The BS2TTS tool should have me pick the Daemon Prince twice given that the model has different "gear" in this case. One with wings and one without wings. And load both models for me seperatly. 

**Upload the Roster**
[RotD 2k New.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4478559/RotD.2k.New.zip)

**Comment by pwestling** [comment]
Ok, turns out I was uniquing models based only on Name + weapon, so I just need to include abilities/upgrades as well. I'll try to get to this by the end of the weekend.

**Comment by Znar1** [comment]
Sounds easy enough. Thank you for your hardwork.

**Comment by pwestling** [comment]
This should (finally) be fixed
