### ISSUE TITLE
Error in Script function

### ISSUE THREAD

**Issue by welshy109** [pwestling/battlescribe-roster-parser#35]
There is an issue now with loading the data sheets when pressing the one on the number pad, it comes up with the error message " Error in Script (unit in question) <onScriptingButtonDown>: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallbacl'. Parameter name: bytes" 

The strange part is, this usually only pops up after you have brought up the datasheet a couple of times mid-game, but once it happens once you can no longer look at the sheets. Don't know if this is due to TTS new update or not.

**Comment by pwestling** [comment]
This is a known issue I've been working on cracking, but it's proven very tough. I'll let you know when it's fixed, but in the mean time I think saving and reloading the table will let you open some additional sheets before it crashes again.

**Comment by pwestling** [comment]
I think this issue should be solved now. If you continue to see the issue, please create a new ticket for me. Thanks!
