### ISSUE TITLE
Dark angels army list not correctly imported.

### ISSUE THREAD

**Issue by Lictor000** [pwestling/battlescribe-roster-parser#36]
**Describe the bug**
Army list not showing some models and some are showing wrong descriptions.

**Expected behavior**
The affected part of the list consist of three units of Ravenwing Bikers(3-3-4 bikes), plus an attack bike each, one with multimelta. 
The Sergeants were equipped with combi-weapons and the bikers with chainswords (one the larger unit has also a flamer).

In the tool output some models are missing: no attack bike with heavy bolter (there are two in the list), no attack bike with the multimelta, no bikers with chainsword and no biker with chainsword and flamer.
Also in the output there are two sergeants models (and that's fine), but the description is weird since they have non of those items (multiple pistols and chainswords on the same model, reported also in the model description e.g. 3xChainswords).

I've tried rebuilding from scratch the list, but there are always similar errors.

Am I doing something wrong?
I'm on battlescribe 2.03.14, W40k 8th 1.4.17 and Dark Angels v135.

**Upload the Roster**
[Ravenwing 1000 pts.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4489749/Ravenwing.1000.pts.zip)
I attach also a screenshot of the output on TTS.
![Immagine](https://user-images.githubusercontent.com/39945124/79507107-68eadb00-8037-11ea-9b75-d504f2df2054.png)

**Comment by pwestling** [comment]
You aren't doing anything wrong. There was at least one bug on my end that seems related. Could you try this on the current version for me and see if it's still a problem? Not sure if this case is covered by the bug fix but I'm hoping it is.

**Comment by Lictor000** [comment]
Hello, I tried again with the same roster and now it works fine! 
Thanks!

**Comment by pwestling** [comment]
Great!
