### ISSUE TITLE
Allow for model variations

### ISSUE THREAD

**Issue by dumptruckman** [pwestling/battlescribe-roster-parser#38]
**Is your feature request related to a problem? Please describe.**
When playing certain armies, there are a lot of variations in the models for the same load out. Examples would be Grots or Troupe Players. Unfortunately, Battlescribe2TTS only allows using one model for a given unit/loadout combination thus denying variation between the models.

**Describe the solution you'd like**
Add a way for users to use multiple models for any given unit/loadout combo. Maybe allow for a pool of models by picking up multiple models at once.

**Comment by dumptruckman** [comment]
Similar to/duplicate of #16

**Comment by pwestling** [comment]
this has been added!
