### ISSUE TITLE
Save Army Code when cutting/copying the bag

### ISSUE THREAD

**Issue by BaconCatBug** [pwestling/battlescribe-roster-parser#39]
**Is your feature request related to a problem? Please describe.**
Right now the code gets cleared when you copy or cut the bag. Putting in the army code will load the army with any models "remembered" intact.

**Describe the solution you'd like**
The army code persists between copies and cuts.

**Comment by pwestling** [comment]
I actually can't find a way to make TTS do this. Unfortunately I don't think it'll be possible.
