### ISSUE TITLE
The Info Script isn't working properly

### ISSUE THREAD

**Issue by Azriel82** [pwestling/battlescribe-roster-parser#40]
**Describe the bug**
When I first load an army that has been saved as an object, pressing the '1' key on the numpad works just fine, as in the unit info window pops up. But then a few minutes go by and then pressing '1' doesn't bring up the info window (or whatever you call it) and instead I get an error message:

![Annotation 2020-04-21 032021](https://user-images.githubusercontent.com/64064929/79837337-3e728800-837f-11ea-987b-90751c526e16.png)

The funny thing is, it'll continue to work on some models, but not others.

Here's the roster:
[1st Brigade 1k pts.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4508312/1st.Brigade.1k.pts.zip)

**Comment by pwestling** [comment]
Thanks for the report! This is a known issue that's really been kicking my butt trying to figure it out. I'll let you know when I crack it. For now, it should fix itself for a while (I think), if you save your game and reload it. Basically the number of open UIs overloads the server and reloading clears them out.

**Comment by pwestling** [comment]
I think this issue should be solved now. If you continue to see the issue, please create a new ticket for me. Thanks!
