### ISSUE TITLE
quote characters not showing properly on unit sheets

### ISSUE THREAD

**Issue by LNLaarhoven** [pwestling/battlescribe-roster-parser#43]
**Describe the bug**
all the single and double quotes are not showing properly anymore on any of my units sheets when I press 1 on the num pad. Old armies that I have seem to be working fine, but when I create new armies we get this small bug.

**Expected behavior**
I expect to see for example 8" instead of 8\&quot; on the unit sheets

**Upload the Roster**
[500PatrolWraithHost.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4530045/500PatrolWraithHost.zip)

**Comment by LNLaarhoven** [comment]
Here is an image of what I see
![bug](https://user-images.githubusercontent.com/6760113/80232717-a235d300-8655-11ea-853b-994a269edabf.png)

**Comment by zephinlucis** [comment]
I'm also having this problem, hopefully it gets fixed soon

**Comment by pwestling** [comment]
Fixed!
