### ISSUE TITLE
Saving model choice

### ISSUE THREAD

**Issue by Chaosari** [pwestling/battlescribe-roster-parser#44]
I have created a roster and generated code, loaded into TTS and selected the appropriate models for my units and generated army.  My only problem is how to save the model selection for future uses in other rosters.
I'm sure it is something simple I am missing.
Thanks in advance.

**Comment by karmington** [comment]
After pressing Create Army just Ctrl+C Copy the ones that spawn on the new rack to the left back to your army setup table?
Also:
"Saved Models
When you select a model with the Battlescribe2TTS tool, the model you've selected is saved into the tool. You can avoid having to re-select models for similar armies in the future by adding the tool to your "Saved Objects" after selecting models. Your selections will be saved and automatically populated in the future for matching units"

**Comment by pwestling** [comment]
Thanks @karmington! Sounds like there's not a bug here, just some unfamiliarity with TTS. You can join the Discord server and get more direct help with this kind of thing: https://discord.gg/EZ6GzW
