### ISSUE TITLE
The tool in TTS in not creating the full army nor full units.

### ISSUE THREAD

**Issue by Athenallus** [pwestling/battlescribe-roster-parser#45]
I tried creating two diferent armies, but it keept missing models from unit (1shining speer loaded out of 7) and some units where just not there (warlock skyrunner, Riptide, etc...). Tried an old list and a new list with BattleScribe updated.

It would create the complete roster that i designed on BattleScribe.

[Eldar_N1.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4534642/Eldar_N1.zip)
[Tau2kNeo.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4534643/Tau2kNeo.zip)

**Comment by Athenallus** [comment]
![Captura de pantalla (131)](https://user-images.githubusercontent.com/64345370/80298461-413ff500-8752-11ea-93d4-fe646f7d0bdd.png)

**Comment by RayShuttlesworth** [comment]
Similar issue happening with my list. Tech-Priest Manipulus is not spawned. 


[2000 - AdMech_ImpKnights Meme.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4546383/2000.-.AdMech_ImpKnights.Meme.zip)

**Comment by pwestling** [comment]
I'm not able to reproduce this locally. Can you guys do the following:
1. Try 2 more times, first to make sure it's happening, and second to make sure the same units are missing each time. Helps me a lot to know if it's a consistent issue or somewhat random
2. Let me know if you see any errors (printed in red) when you create the armies in a single player game?

**Comment by RayShuttlesworth** [comment]
So after using that army my Manipulus ended up appearing at some point but it was not visible for a long time. I drag selected another unit and when they were picked up he appeared and was fallen over. It was odd. I'll report if it happens again.

**Comment by pwestling** [comment]
Please open a new ticket if you see further issues on this. Thanks!
