### ISSUE TITLE
Create Army is throwing me an error

### ISSUE THREAD

**Issue by PhilosophicalPsycho** [pwestling/battlescribe-roster-parser#48]
![image](https://user-images.githubusercontent.com/34174406/80909212-7fea2800-8cdb-11ea-99eb-7de9c6061c4f.png)

**Comment by StanHilliar** [comment]
Same issue when creating an IG army from list. 
All models present and added to list before selecting "create army".

![Battlescribe2ttsError](https://user-images.githubusercontent.com/28047251/80985632-c3ee4180-8e2f-11ea-9569-41aa1ecf51bb.png)

Expecting a successful army creation.
This had been working Last Friday 1st May

**Comment by PhilosophicalPsycho** [comment]
I tried it on another computer and I was able to make a grey knights list but not my IG list. I don't know if it broke my ability to make other faction lists but I do think it's only happening for something in IG. Here is my list if it helps.


++ Brigade Detachment +12CP (Imperium - Astra Militarum) [92 PL, 10CP, 1,548pts] ++

+ Configuration +

Battle-forged CP [3CP]

Detachment CP [12CP]

Regimental Doctrine: Regiment: Cadian

+ Stratagems +

Imperial Commander's Armoury [-1CP]: 1 additional Heirloom of Conquest

Operative Requisition Sanctioned [-2CP, 95pts]

Specialist Detachment [-1CP]: Emperor's Fist Tank Company

Tank Ace [-1CP]

+ HQ +

Knight Commander Pask [13 PL, 234pts]: Battle Cannon, Display Tank Orders, Lascannon, Plasma Cannons

Tank Commander [12 PL, 199pts]: Battle Cannon, Display Tank Orders, Emperor's Fist, Lascannon, Plasma Cannons, Relic (Emperor's Fist): Hammer of Sunderance, Slow and Purposeful, Warlord

Tank Commander [12 PL, 199pts]: Battle Cannon, Display Tank Orders, Emperor's Fist, Lascannon, Plasma Cannons, Relic: Kurov's Aquila, Up-armoured

+ Troops +

Infantry Squad [3 PL, 40pts]
. 9x Guardsman: 9x Lasgun
. Sergeant: Chainsword, Laspistol

Infantry Squad [3 PL, 40pts]
. 9x Guardsman: 9x Lasgun
. Sergeant: Chainsword, Laspistol

Infantry Squad [3 PL, 40pts]
. 9x Guardsman: 9x Lasgun
. Sergeant: Chainsword, Laspistol

Infantry Squad [3 PL, 40pts]
. 9x Guardsman: 9x Lasgun
. Sergeant: Chainsword, Laspistol

Infantry Squad [3 PL, 40pts]
. 9x Guardsman: 9x Lasgun
. Sergeant: Chainsword, Laspistol

Infantry Squad [3 PL, 40pts]
. 9x Guardsman: 9x Lasgun
. Sergeant: Chainsword, Laspistol

+ Elites +

Astropath [1 PL, 15pts]: Laspistol, Psychic Maelstrom

Astropath [1 PL, 15pts]: Laspistol, Nightshroud

Astropath [1 PL, 15pts]: Laspistol, Psychic Barrier

+ Fast Attack +

Hellhounds [6 PL, 101pts]
. Hellhound: Heavy Bolter, Turret-mounted Inferno Cannon

Hellhounds [6 PL, 101pts]
. Hellhound: Heavy Bolter, Turret-mounted Inferno Cannon

Salamander Scout Tank [5 PL, 73pts]
. Salamander Scout Tank: Autocannon, Heavy bolter

+ Heavy Support +

Basilisks [7 PL, 108pts]
. Basilisk: Heavy Bolter

Basilisks [7 PL, 108pts]
. Basilisk: Heavy Bolter

Heavy Weapons Squad [3 PL, 45pts]
. Heavy Weapon Team: Mortar
. Heavy Weapon Team: Mortar
. Heavy Weapon Team: Mortar

++ Super-Heavy Auxiliary Detachment (Imperium - Imperial Knights) [25 PL, -2CP, 452pts] ++

+ Configuration +

Detachment CP

Household Choice: Questor Mechanicus
. House Krast

+ Stratagems +

Exalted Court [-1CP]: Exalted Court: 1 Extra Warlord Trait

Heirlooms of the Household [-1CP]: Heirlooms of the Household: 1 Extra Heirloom

+ Lord of War +

Knight Crusader [25 PL, 452pts]: Character (Exalted Court), Character (Heirloom of the House), Heavy Stubber, Heirloom: Armour of the Sainted Ion, Thermal Cannon, Warlord Trait (Krast): First Knight
. Avenger Gatling Cannon w/ Heavy Flamer: Avenger Gatling Cannon, Heavy Flamer

++ Total: [117 PL, 8CP, 2,000pts] ++

Created with BattleScribe (https://battlescribe.net)

**Comment by pwestling** [comment]
This should be fixed now
