### ISSUE TITLE
List cut off

### ISSUE THREAD

**Issue by Carparts1** [pwestling/battlescribe-roster-parser#49]
![Capture](https://user-images.githubusercontent.com/64732139/80912891-dbc9a680-8d05-11ea-8a62-153fba47adc3.PNG)
as the title says

I expected my whole list to show up

[genestealers main - Copy.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4570145/genestealers.main.-.Copy.zip)

**Comment by pwestling** [comment]
This should be fixed now
