### ISSUE TITLE
Error when clicking "create army"

### ISSUE THREAD

**Issue by Carparts1** [pwestling/battlescribe-roster-parser#50]
![2](https://user-images.githubusercontent.com/64732139/80912921-0e739f00-8d06-11ea-9ba0-ac0c023ae1bb.PNG)

An error when clicking "create army"  all models had been selected

I expected my army to be created, as it has before with these units

[genestealers main 2 - Copy.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4570152/genestealers.main.2.-.Copy.zip)

**Comment by Carparts1** [comment]
repeated and got issue again for the third time

**Comment by pwestling** [comment]
This should be fixed now
