### ISSUE TITLE
Error when clicking "create army" but different than my last

### ISSUE THREAD

**Issue by Carparts1** [pwestling/battlescribe-roster-parser#51]
![3](https://user-images.githubusercontent.com/64732139/80913062-2992de80-8d07-11ea-8b6f-a068f1ed053a.PNG)

issue is as title says. All unit spots were filled with models.

I expected it to create my army as it has before and for these same units.

[genestealers main 1 - Copy.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4570162/genestealers.main.1.-.Copy.zip)

**Comment by pwestling** [comment]
This should be fixed now
