### ISSUE TITLE
Network Error when uploading list

### ISSUE THREAD

**Issue by BigMoneyJesus** [pwestling/battlescribe-roster-parser#52]
**Describe the bug**
When I try to upload a list to your site a little text box pops up saying network error and it does not generate a code. I know my internet is working as I am playing tabletop simulator with friends online right now. 
![Battlescribe](https://user-images.githubusercontent.com/64740083/80917216-c8750600-8d1a-11ea-8a7c-c86b698be1f0.png)

**Expected behavior**
It should generate a code.

**Upload the Roster**
I have tried it with several different rosters. 

[500_Thousand_Sons - Copy.rosz.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4570798/500_Thousand_Sons.-.Copy.rosz.zip)

**Comment by Carparts1** [comment]
I'm getting the same issue. Server is down at the moment it seems.

**Comment by Goblin137** [comment]
I'm having the same issue.]

I've posted this on another error topic but I'll put it here too. 

The site says NetworkError and the console shows the following

(https://user-images.githubusercontent.com/64739752/80916988-15290300-8d54-11ea-8bf8-0f45118f9a44.PNG)

Any thoughts?

Edit: I've tried this on Chrome and Microsoft Edge browsers with the same outcome.

**Comment by knutwal** [comment]
I tried a 300 pt test list with file size 6kB and it works. Just maybe it helps to solve the bug.

**Comment by BigMoneyJesus** [comment]
After seeing your 300 points I went and tested and noticed all my lists under 500 points are working. Bigger than that and the network error pops up for me.

**Comment by knutwal** [comment]
yeah completely random. A single 45 pt unit did not work, a 1000 pt. army did work but only import one single unit to TTS

**Comment by pwestling** [comment]
I think the issues with the server should be fixed now for all lists. Please open a new ticket if you see otherwise. Thanks!
