### ISSUE TITLE
Error when clicking "Create Army"

### ISSUE THREAD

**Issue by Mitlof** [pwestling/battlescribe-roster-parser#53]
After making an army and clicking the create army button, this error pops up and nothing happens. I was able to create armies fine half an hour ago and with these models. My internet was up fine.

![image](https://user-images.githubusercontent.com/46531854/80927943-70cdad80-8da1-11ea-8e5a-9d98262f166a.png)

**Comment by VoXesh** [comment]
> After making an army and clicking the create army button, this error pops up and nothing happens. I was able to create armies fine half an hour ago and with these models. My internet was up fine.
> 
> ![image](https://user-images.githubusercontent.com/46531854/80927943-70cdad80-8da1-11ea-8e5a-9d98262f166a.png)

I too have received this error.

**Comment by knutwal** [comment]
<img width="307" alt="Unbenannt" src="https://user-images.githubusercontent.com/64744296/80995828-2dc21780-8e3f-11ea-8f2d-4fa37e7e9caf.png">

**Comment by knutwal** [comment]
with current workshop BS2TTS

**Comment by Mitlof** [comment]
Re-downloading a clean workshop copy of the mod fixed the issue for me

**Comment by pwestling** [comment]
This should be fixed now
