### ISSUE TITLE
Non-assigned Equipment Creating an Extra Unit 

### ISSUE THREAD

**Issue by Znar1** [pwestling/battlescribe-roster-parser#54]
**Describe the bug**
Scarab Occult Terminators have the option of a Hellfyre Missile Rack that is not assigned to a particular model within Battlescribe. Thus when BSTTS converts it, it see's the option as an additional Terminator. Thus I end up with an extra Terminator. 

**Expected behavior**
It should be added to one of the existing Terminators instead of adding a new model. If I pay for a unit of 5 Terminators (4 Terminators + Sorcerer) it should add to one of the 4 terminators as an option. 

**Upload the Roster**
[TTS Tourney Roster.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4577499/TTS.Tourney.Roster.zip)

**Comment by pwestling** [comment]
This should be fixed
