### ISSUE TITLE
list is still cut off

### ISSUE THREAD

**Issue by Carparts1** [pwestling/battlescribe-roster-parser#55]
My list is still being cut off

![aaaw](https://user-images.githubusercontent.com/64732139/81104774-a2956000-8ed8-11ea-8da8-1d4b35ddb19b.PNG)

[genestealers hordes - Copy.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4583067/genestealers.hordes.-.Copy.zip)

**Comment by Carparts1** [comment]
I tried increasing Ui Width and height but they did nothing

**Comment by pwestling** [comment]
I've not heard about this from anywhere else. Please try again with a new army and the latest mod, I expect you'll no longer see this issue.
