### ISSUE TITLE
error when creating army

### ISSUE THREAD

**Issue by Carparts1** [pwestling/battlescribe-roster-parser#56]
error when creating army
![aaaaaaad](https://user-images.githubusercontent.com/64732139/81105199-30714b00-8ed9-11ea-9349-4835a8cb9b55.PNG)

expected to create army

[genestealers hordes 1 - Copy.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4583084/genestealers.hordes.1.-.Copy.zip)

**Comment by pwestling** [comment]
I've not heard about this from anywhere else. Please try again with a new army and the latest mod, I expect you'll no longer see this issue.
