### ISSUE TITLE
error when creating army

### ISSUE THREAD

**Issue by Carparts1** [pwestling/battlescribe-roster-parser#57]
error when creating army

I expected it to create my army

[genestealers hordes 2 - Copy.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4583106/genestealers.hordes.2.-.Copy.zip)
![asdasd](https://user-images.githubusercontent.com/64732139/81105793-171cce80-8eda-11ea-889a-0c3c294da6ad.PNG)

**Comment by pwestling** [comment]
This looks to me like you're using an outdated version of the workshop mod. Can you make sure you're using a new copy of the tool from the Battlescribe2tts workshop mod for me?

**Comment by pwestling** [comment]
I've not heard about this from anywhere else. Please try again with a new army and the latest mod, I expect you'll no longer see this issue.
