### ISSUE TITLE
Infinite duplicate because not last unit

### ISSUE THREAD

**Issue by Ryumidori** [pwestling/battlescribe-roster-parser#58]
**Describe the bug**
When deleting or storing units some model get asigned to be the last model.
This causes it be unable to be deleted or spawns infinite copies when trying to put the unit in a bag to store

**Expected behavior**
The expected behavior is that i the player get to decide which model to take away during play not for the script to make it impossible. 

**Upload the Roster**
In this roster its 1 of the seraphim units
[Sisters for 10k list.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4584502/Sisters.for.10k.list.zip)

**Comment by pwestling** [comment]
This has been changed
