### ISSUE TITLE
battlescribe card view (action 1) does not include unit's Selection Rules

### ISSUE THREAD

**Issue by Tetlanesh** [pwestling/battlescribe-roster-parser#59]
**Describe the bug**
I have a deathguard plague marines unit in my roster. It have following rules visible when viewing with BattleScribe "View Selection" option on the unit:

> Selection Rules
> Hateful Assault: If this unit makes a charge move, is charged or performs a Heroic Intervention, add 1 to the Attacks characteristic of models in this unit until the end of the turn.

Above is displayed below 
Also in the Rules section of the display it reads:

> Rules: Hateful Assault

This is not included in the card displayed in the TTS

**Expected behavior**
I would expect Selections rules relevant to a given unit to be displayed on a card in TTS for each of the model in that unit

**Upload the Roster**
Rename your .rosz file to have the .zip extension, then drag and drop it here
[Solo DG 1500 v2 — kopia.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4605958/Solo.DG.1500.v2.kopia.zip)

**Comment by pwestling** [comment]
This should be fixed now
