### ISSUE TITLE
Datasheet rendering autonomously and improperly; cannot dismiss

### ISSUE THREAD

**Issue by kharnaxe** [pwestling/battlescribe-roster-parser#6]
**Describe the bug**
On creating an army, once models are placed the datasheet UI window opens by itself. The datasheet is incomplete, semi-transparent, and missing the UI elements needed to close it. The 'Scripting 1' command is unresponsive, and cannot open another datasheet on any other model.  

he console reports a UI XML bug. 

The error appears both on a 'fresh' load of the mod (assigning models) and using a saved object. 

**Expected behavior**
The models to load in, and no datasheet to appear until I opened the UI using a 'Scripting 1' command. 

**Screenshot**
![BSTTSbug](https://user-images.githubusercontent.com/52875307/61179751-92ac4700-a64c-11e9-9ac7-108a0de52579.jpg)

**Upload the Roster**
[Nids 1k.zip](https://github.com/pwestling/battlescribe-roster-parser/files/3389498/Nids.1k.zip)

**NB**
This mod is amazing and you should be knighted.

**Comment by pwestling** [comment]
Just deployed a fix for this - turns out the damage track for Trygons have an "&" in the title, which the code was failing to escape, making the XML invalid. Thanks for the bug report! This was super helpful. Going to close but please reopen or make a new issue if you see anything else.
