### ISSUE TITLE
To many models used after "creating army"

### ISSUE THREAD

**Issue by Tetlanesh** [pwestling/battlescribe-roster-parser#60]
**Describe the bug**
I have a roster with a unit of 7 plague marines:

- champion
- 2 guys with flails of corruption
- one guy with second plague knife
- 3 guys with bubotic axes

The list of model types to select generated by Battlescribe2tts contains:

1. Model: plague Chamption (+listed equipment)
2. Model: Plague Marine w/ melee weapon (+equipment list incluging flai of corruption)
3. Model: Plague Marine w/ melee weapon (+equipment list, no mention of flail, axe or second knife)
4. Model: Plague Marine w/ melee weapon (+equipment list incluging bubotic axe)
5. Model: 2nd Plague knife (that's all it says)
6. Model: Bubotic Axe; Weapon: Bubotic Axe

The final unit generated by bs2tts using "Create Army" contains:

- 1 x model 1 (using numbers from above list)
- 2 x model 2
- 1 x model 3
- 3 x model 4
- 1 x model 5
- 3 x model 6

A total of 11 models instead of 7

**Expected behavior**
unit composition in tts matching roster

**Upload the Roster**
Rename your .rosz file to have the .zip extension, then drag and drop it here

[Solo DG 1500 v2 — kopia.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4605968/Solo.DG.1500.v2.kopia.zip)

**Comment by pwestling** [comment]
This should be fixed now
