### ISSUE TITLE
Plague Marine Sqaud Issues 

### ISSUE THREAD

**Issue by welshy109** [pwestling/battlescribe-roster-parser#61]
**Describe the bug**
### Issue when trying to make a Plague Marine Squad, There seems to be missing data files on the plague marines and when in TTS and you plug in the code it only shows you the Plague Champion istead of the whole squad. 

**Expected behavior**
When in you put the roster code into TTS it puts all of the squads information into the plague champ (sergeant), and there are no selections for the other marines in the squad. 
**Upload the Roster**
Rename your .rosz file to have the .zip extension, then drag and drop it here

**Comment by pwestling** [comment]
Can you upload a roster where you're seeing this issue? Helps me to know I'm tackling the right problem.

**Comment by TypeI** [comment]
Hello, I don't mean to resurrect this issue, but it seems like I'm seeing this problem still. When submitting the code, the buttons for my models represent multiple models. Then when I attempt to "create army" only a single model is generated. here is the roster file I'm using. You can see that both the Plage marines with blight launchers and the plague marines with bolt guns are only created as single models with 2x weapons. I've tried selecting and picking up duplicates when assigning models and it returns the same results.  .rosz provided
[Dg spec.zip](https://github.com/pwestling/battlescribe-roster-parser/files/5044374/Dg.spec.zip)

**Comment by pwestling** [comment]
This should be fixed now
