### ISSUE TITLE
Scripting buttons 2-5 triggering multiple times

### ISSUE THREAD

**Issue by arne-z** [pwestling/battlescribe-roster-parser#62]
**Describe the bug**
On some models Wound counter and circle display increment and decrement multiple times with a single press of the scripting button.
Specifically, on Deathwatch Intercessors Wounds and circle display are incremented or decremented by 3, Deathwatch Veterans are incremented and decremented by 2, and Ravenwing Talonmasters by 6 for a single click of the scripting button.

**Expected behavior**
Each time the Scripting button is pressed the wound counter or circle display should, depending on the button pressed increment or decrement by 1.

[DeathwatchDoubleBattalion.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4631225/DeathwatchDoubleBattalion.zip)

**Comment by pwestling** [comment]
This issue should be fixed for newly-created armies going forward
