### ISSUE TITLE
Range Measure Script issues with Oval Bases

### ISSUE THREAD

**Issue by Superbeast75** [pwestling/battlescribe-roster-parser#63]
When using the range measurement feature (4 and 5 on Keypad) models with an Oval base are using the wrong size base.

Should be using an oval base as the range differs on Oval bases, check out the Exocrines as an example.

[2000 Point Tyranids Leviathan and Kronos.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4632964/2000.Point.Tyranids.Leviathan.and.Kronos.zip)

![image](https://user-images.githubusercontent.com/65390874/82025006-9c497580-9688-11ea-9890-8bd5d715a02f.png)

**Comment by pwestling** [comment]
The code does not work for oval bases right now. Planning to make this work, going to re-label this as an enhancement.

**Comment by pwestling** [comment]
This should be fixed - it should now auto detect these kinds of bases, and the new control panel will let you select a base size when auto detection does not work
