### ISSUE TITLE
Receiving Network Error

### ISSUE THREAD

**Issue by AtemAndrew** [pwestling/battlescribe-roster-parser#7]
Unable to upload a roster through the tool proper. Tried with multiple rosters, as seen [here](https://imgur.com/a/Xwjyghg). Affecting multi-unit and single-unit armies. Tried multiple browsers and clearing cache and cookies. Unfortunately whatever the dev tried doing to fix it didn't work.
[Warhammer Armies.zip](https://github.com/pwestling/battlescribe-roster-parser/files/3394212/Warhammer.Armies.zip)

**Comment by pwestling** [comment]
The upload is currently working for me with these rosters. I know you said you cleared the cache, but could you try one more cache-related thing - try clicking the page reload button in the browser while holding the Shift key, then re-try the upload. I can't be sure they're you, but I'm seeing requests that are still going to the wrong backend address (which was the issue I fixed earlier).

**Comment by AtemAndrew** [comment]
Yup, that did it. Sorry. Had some stuff going so I wasn't able to do a com reset, didn't think to do a hard page reset since I did the browser clear and reset.

**Comment by pwestling** [comment]
Glad it all worked in the end!
