### ISSUE TITLE
Deathwatch: BS2TTS will not populate Hellblasters in Intercessor Squads.

### ISSUE THREAD

**Issue by CorpseEmperor** [pwestling/battlescribe-roster-parser#73]
**Describe the bug**
When creating a squad of Intercessors with Blot Rifles with 4 Intercessors, 1 SGT and 5 Hellblasters with Plasma Incinerators it doesn't give the option to select a model for the Hellblasters instead only offering choices to select a Intercessor or Intercessor SGT that is equiped with both the Bolt Rifle and Plasma Incinerator. I remember this working correctly a few months ago. Thanks for this amazing app!

**Expected behavior**
I expect for BS2TTS to give me the option to select the model for the Hellblaster.

**Upload the Roster**
This folder only contains the specific unit that is bugged 

[DWInterHelblastBS2TTStst.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4767747/DWInterHelblastBS2TTStst.zip)

**Comment by pwestling** [comment]
It looks to me like the underlying discrepancy in the battscribe data has been solved, and these units now work correctly. Re-save your list in battlescribe with the updated data and it should work.
