### ISSUE TITLE
Single Stormraven Gunship creating multiple entries for Table Top Simulator to fill

### ISSUE THREAD

**Issue by DarquanZA** [pwestling/battlescribe-roster-parser#76]
**Describe the bug**
When importing a GK army list including a Stormraven Gunship, it created 4 entries to be filled. If I fill all 4, the army creates 4 models. When I delete the additional 3 to save and import into a game, the script key 1 does not work for the Stormraven.

**Expected behavior**
A single Stormraven Gunship entry to be created in the tool, and then a single model to be created for the army.

**Upload the Roster**
[1000pt Raven Purifiers .zip](https://github.com/pwestling/battlescribe-roster-parser/files/4840202/1000pt.Raven.Purifiers.zip)

Roster Entry:
![Battle Scribe Entry for Stormraven](https://user-images.githubusercontent.com/67500715/85918395-b5863a00-b862-11ea-9057-c994c75fadf9.jpg)

As Created in TTS:
![Army as Created](https://user-images.githubusercontent.com/67500715/85918344-46104a80-b862-11ea-9462-a71647a43c1d.jpg)

**Comment by xuvvy** [comment]
Same bug with Grey Knights infantry units and their throwables. It creates one entry per throwable and fourth entry without any throwables.

**Comment by cpugeek** [comment]
Just came across this issue as well.  It looks like it might be a battlescribe bug since on an Ultramarines Stormraven the first line of the datacard is selections where as with the Grey Knights its the Categories and there is no selections line for the GK Stormraven which is what I am guess is causing the parsing issue.

**Comment by pwestling** [comment]
Pushing out a fix for this now. Grey Knight grenades should be fixed as well.
