### ISSUE TITLE
Grey Knights infantry units' throwables split up into separate units

### ISSUE THREAD

**Issue by xuvvy** [pwestling/battlescribe-roster-parser#77]
**Describe the bug**
When it comes to Grey Knights infantry units (Strike Squad, Terminators, Paladins, etc.) their throwable items (Frag grenades, Krak grenades and Psyk-out grenades), are separated into 4 different units: 
1. the unit with frag grenades, 
2. the unit with krak grenades,
3. the unit with psyk-out grenades,
4. the unit without any throwables.

If any of those four are not selected when army is created it means that certain models from a unit will be missing. E.g. I would selected the number 4. without any throwables and just add a note in TTS that they have all three throwables, but that means not selecting the other three during army creation which means I will only have 1/4 of the units spawned in when army is created because these throwables are split among models in the unit rather than all throwables being given to all models in the unit, or more precisely them having all throwables as one unit.

The bug can be seen in the image.
![image](https://user-images.githubusercontent.com/21984783/86249603-ca8b0200-bbaf-11ea-8120-f790885267cc.png)

**Expected behavior**
Expected behavior is for there to be a single unit with two or all three throwables, as per game rules units have all the throwables, but can only use one of them. So, where there is supposed to be one unit, one card now there is four cards, four units.

**Upload the Roster**
[Grey Knights 2000pts 02 (Comp).zip](https://github.com/pwestling/battlescribe-roster-parser/files/4858135/Grey.Knights.2000pts.02.Comp.zip)

**Comment by Streyder** [comment]
Also sometimes, Psych-Out Grenades are not removed from the description although you click "Exclude Granades"

**Comment by pwestling** [comment]
Pushing out a fix for this now
