### ISSUE TITLE
Celestine aura base size doesn't change

### ISSUE THREAD

**Issue by Connor-Crees** [pwestling/battlescribe-roster-parser#78]
**Describe the bug**
When attempting to change the base size for auras (with numpad 6 & 7) for the Celestine model, the following error occurs:
Error in Script (6/6 Celestine - d2c6b0) function <onScriptingButtonDown>: chunk_3:(576,2-23): table index is nil

**Expected behavior**
For the base size on the aura to change as with other models.

**Upload the Roster**
[just celestine.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4858202/just.celestine.zip)

**Comment by pwestling** [comment]
Is this still an issue for you?

**Comment by Connor-Crees** [comment]
No, it seems to have been fixed
