### ISSUE TITLE
Option to place wound Tooltip at the start of the name

### ISSUE THREAD

**Issue by BaconCatBug** [pwestling/battlescribe-roster-parser#8]
**Is your feature request related to a problem? Please describe.**
Right now models with long names are a minor inconvenience to track wounds with as it can wrap off the edge and become impossible to select.

**Describe the solution you'd like**
Either an option to or a change to place the wounds amount to the front of the name. e.g. 12/12 Swarmlord instead of Swarmlord 12/12

**Comment by pwestling** [comment]
This sounds like just a better way to format things. I'll make the change - thanks for the suggestion!

**Comment by pwestling** [comment]
This was done a while ago
