### ISSUE TITLE
Plague Marines (9th ed) Issues with Spawning and Stats

### ISSUE THREAD

**Issue by BD1980** [pwestling/battlescribe-roster-parser#82]
**Describe the bug**
When generating a Plague Marine army (created with latest battlescribe) multiple issues appear to be present. While the stats in battlescribe appear correct, they are not correct when generated with battlescribe2tts. Still AMAZING product you have here!

1. When the army is generated it is only generating 2 of the models chosen
2. When the army is generated it doubles the attacks for models it should not. For instance in the attached roster, the Plague Marines with a Blight launcher should have 1 attack as they appear in battlescribe. When generated they get 2 attacks, which is incorrect.
3. When the army is generated it is DOUBLING up some weapons. For instance the attached army it doubles the Blight Launcher for each model that selected it. I also see it incorrectly adding more Blight Grenades then it should.

4. When the army is generated with 2x Plague Knives,  it is also adding one additional Plague Knife for a total 3x.

**Expected behavior**
1. While I'm not sure why some models are not spawned in at all, all 5 models should be spawned. 
2. Only the Captain and Marines with 2x plague knives should get 2 attacks
3. When choosing a Blight Launcher you should have 1 Attack
4. When choosing 2x Plague Knives you should only get 2x plague knives not 3x.

**Upload the Roster**
Rename your .rosz file to have the .zip extension, then drag and drop it here
[DG_1k.zip](https://github.com/pwestling/battlescribe-roster-parser/files/5066200/DG_1k.zip)

**Comment by pwestling** [comment]
Just pushed a change which should hopefully fix this issue
