### ISSUE TITLE
Suggestion: Map Creator

### ISSUE THREAD

**Issue by AtemAndrew** [pwestling/battlescribe-roster-parser#9]
**Is your feature request related to a problem? Please describe.**
Issue not related to problem

**Describe the solution you'd like**

This would likely be a separate project, but why not use a similar tool to create maps? Just as users can import models to use in the current tool, have them import a tile or two used in map creation as the 'base', allow them to input  the size of the map, and have them select 1 or 2 map additions (such as trees or rocks) and a set piece (such as a large crater), etc.

**Comment by pwestling** [comment]
Out of scope for this project unfortunately. BaconCatBug has a great system for terrain stuff.
